Added mobilenet_v1 folder
pclubiitk/model-zoo pull request #77
Opened 2021-06-15 16:33 UTC by hitesh-anand

the file named "mobilenet-v1" was added accidentally.
The main files are inside the folder named "mobilenet_v1"

2021-06-18 17:39 UTC, SomTambe requested changes
It was informed well before that jupyter notebooks won't be accepted. Please help us in maintaining consistency with the rest of the repo. Others have done it too.

2021-06-18 17:39 UTC, SomTambe commented on classification/mobilenet_v1/README.txt
> +
Rewrite the README in Markdown. Let it be consistent with the rest of the repo.

2021-06-18 17:39 UTC, SomTambe commented on classification/mobilenet-v1
> +
Why can't you delete this file?

2021-06-18 19:16 UTC, hitesh-anand commented
Deleted the earlier added Jupyter notebook files and README, added a new README written using markdown and a .py file containing the mobilenet model implemented in Google Collab.

2021-06-21 08:14 UTC, namangup commented
Look at the pytorch version of MobileNet to get an idea of what is expected. Lot of changes required.

2021-06-21 08:22 UTC, closed without merging